{{- if .Values.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-staging
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "1"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-staging-clusterissuer-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
{{- end }}
---

{{- if .Values.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-prod
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "1"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-prod-clusterissuer-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik

{{- end }}