{{- if and .Values.serviceAccount.create .Values.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "certmanager.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "certmanager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
