apiVersion: v1
kind: Service
metadata:
  name: {{ include "dhis2-helm.fullname" . }}-hl
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "dhis2-helm.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dhis2-helm.selectorLabels" . | nindent 4 }}
