{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dhis2-helm.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "dhis2-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
