{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dhis2-helm.fullname" . }}
  labels:
    {{- include "dhis2-helm.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "dhis2-helm.fullname" . }}-hl
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      {{- include "dhis2-helm.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      partition: {{ .Values.strategy.rollingUpdate.partition }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dhis2-helm.selectorLabels" . | nindent 8 }}
      {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dhis2-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: dhis2-home-permissions
          image: busybox
          command: [ 'sh', '-c', 'chown {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }} {{ .Values.dhis2Home }} && chmod u+rw,go-rwx {{ .Values.dhis2Home }}' ]
          volumeMounts:
            - name: {{ include "dhis2-helm.fullname" . }}
              mountPath: {{ .Values.dhis2Home }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CATALINA_OPTS
              value: {{ .Values.catalinaOpts }}
            - name: JAVA_OPTS
              value: "-Dlog4j2.configurationFile={{ .Values.dhis2Home }}/log4j2.xml {{ .Values.javaOpts }}"
            - name: DHIS2_HOME
              value: {{ .Values.dhis2Home }}
          envFrom:
            {{- range .Values.configMaps }}
            - configMapRef:
                name: {{ .name }}
                optional: false
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: http
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
          {{- end }}
          volumeMounts:
            - name: {{ include "dhis2-helm.fullname" . }}
              mountPath: {{ .Values.dhis2Home }}
              readOnly: false
            - name: dhis-conf
              mountPath: {{ .Values.dhis2Home }}/dhis.conf
              subPath: dhis.conf
            - name: google-auth-json
              mountPath: {{ .Values.dhis2Home }}/dhis-google-auth.json
              subPath: dhis-google-auth.json
            - name: log4j2-xml
              mountPath: {{ .Values.dhis2Home }}/log4j2.xml
              subPath: log4j2.xml
            - name: server-xml
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
            - name: context-xml
              mountPath: /usr/local/tomcat/conf/context.xml
              subPath: context.xml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: dhis-conf
          configMap:
            name: {{ include "dhis2-helm.fullname" . }}
            items:
              - key: dhis.conf
                path: dhis.conf
        - name: google-auth-json
          configMap:
            name: {{ include "dhis2-helm.fullname" . }}
            items:
              - key: dhis-google-auth.json
                path: dhis-google-auth.json
        - name: server-xml
          configMap:
            name: {{ include "dhis2-helm.fullname" . }}
            items:
              - key: server.xml
                path: server.xml
        - name: log4j2-xml
          configMap:
            name: {{ include "dhis2-helm.fullname" . }}
            items:
              - key: log4j2.xml
                path: log4j2.xml
        - name: context-xml
          configMap:
            name: {{ include "dhis2-helm.fullname" . }}
            items:
              - key: context.xml
                path: context.xml
  {{- if .Values.storage.persisted }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "dhis2-helm.fullname" . }}
        labels:
          {{- include "dhis2-helm.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage.volumeSize }}
  {{- end }}
{{- end }}