{{- if and .Values.pdb.create (eq .Values.mode "cluster") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: broker
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}
{{- end }}
