{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: broker
  annotations:
    # The data directories are formatted with this id. If the Secret is deleted
    # and recreated with a new id, the brokers will not start.
    helm.sh/resource-policy: keep
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  cluster-id: {{ include "kafka.clusterId" . | b64enc | quote }}
{{- end }}
