apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-connect
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: connector
spec:
  ports:
    - protocol: TCP
      port: 8083
      targetPort: connector
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: connector