{{- if and .Values.storage.persisted  }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "byod-manager.fullname" . }}
  labels:
    {{- include "byod-manager.labels" . | nindent 10 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.volumeSize }}
  storageClassName: {{ .Values.storage.className }}
{{- end }}