apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "byod.fullname" . }}-solr-init
  labels:
    {{- include "byod.labels" . | nindent 4 }}
data:
  ZK_HOST_VAR: {{ print (include "byod.fullname" . | upper) "_ZOOKEEPER_SERVICE_HOST" }}
  ZK_PORT_VAR: {{ print (include "byod.fullname" . | upper) "_ZOOKEEPER_SERVICE_PORT" }}
  create-collections.sh: |
    #!/bin/bash
    set -e
    
    echo "Waiting for Zookeeper to be ready..."
    # Get the first ZK host from the comma-separated list
    FIRST_ZK_HOST=$(echo "${SOLR_ZK_HOSTS}" | cut -d'/' -f1 | cut -d',' -f1)
    until nc -z ${FIRST_ZK_HOST%:*} ${FIRST_ZK_HOST#*:}; do
      echo "Waiting for Zookeeper at ${FIRST_ZK_HOST}..."
      sleep 5
    done
    
    echo "Waiting for Solr to be ready..."
    until curl -s "http://$HOSTNAME:8983/solr/admin/collections?action=LIST"; do
      sleep 5
    done
    
    # Create collections
    curl "http://$HOSTNAME:8983/solr/admin/collections?action=CREATE&name=products&numShards=3&replicationFactor=2"

  init-solr.sh: |-
    #!/bin/bash
    set -e

    echo "Waiting for Zookeeper to be ready..."
    ZK_HOST="${ZK_HOST_VAR}"
    ZK_PORT="${ZK_PORT_VAR}"
    until nc -z $ZK_HOST $ZK_PORT ; do
      echo "Waiting for Zookeeper at $ZK_HOST $ZK_PORT ..."
      sleep 5
    done
    

    echo "Uploading configset to ZooKeeper..."
    /opt/bitnami/solr/bin/solr zk upconfig -n bombeke_dev \
      -d /configsets/conf \
      -z ${SOLR_ZK_HOSTS}

    echo "Creating collection..."
    curl "http://{{ include "byod.fullname" . }}-solr:8983/solr/admin/collections?action=CREATE&name=bombekecollection&numShards=1&replicationFactor=1&collection.configName=bombeke_dev" \
      -u "{{ .Values.solr.auth.adminUsername }}:{{ .Values.solr.auth.adminPassword }}"

    echo "Building spellcheck dictionary..."
    curl "http://{{ include "byod.fullname" . }}-solr:8983/solr/bombekecollection/spell?spellcheck.build=true" \
      -u "{{ .Values.solr.auth.adminUsername }}:{{ .Values.solr.auth.adminPassword }}"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "byod.fullname" . }}-solr-config
  labels:
    {{- include "byod.labels" . | nindent 4 }}
data:
  solrconfig.xml: |-
    {{- .Files.Get "configsets/bombeke_dev/conf/solrconfig.xml" | nindent 4 }}
  stopwords.txt: |-
    {{- .Files.Get "configsets/bombeke_dev/conf/stopwords.txt" | nindent 4 }}
  schema.xml: |-
    {{- .Files.Get "configsets/bombeke_dev/conf/schema.xml" | nindent 4 }}
  synonyms.txt: |-
    {{- .Files.Get "configsets/bombeke_dev/conf/synonyms.txt" | nindent 4 }}