{{- if and .Values.storage.persisted  }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "byod.fullname" . }}
  labels:
    {{- include "byod.labels" . | nindent 10 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.volumeSize }}
  storageClassName: {{ .Values.storage.className }}
{{- end }}