{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smartai.fullname" . }}
  labels:
    {{- include "smartai.labels" . | nindent 4 }}
data: 
  config.ini: |
    {{- .Values.configIni | nindent 4 }}
  cert_public.pem: |
    {{- .Values.certPublicPem | nindent 4 }}
{{- end }}   
