apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "smartai.fullname" . }}
  labels:
    {{- include "smartai.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "smartai.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "smartai.fullname" . }}  # Required for StatefulSet
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "smartai.selectorLabels" . | nindent 8 }}  # Changed to selectorLabels for consistency
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "smartai.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: smartai-home-permissions
          image: busybox
          command: ['sh', '-c', 'mkdir -p {{ .Values.smartaiHome }} && chown {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }} {{ .Values.smartaiHome }} && chmod 750 {{ .Values.smartaiHome }}']
          volumeMounts:
            - name: data
              mountPath: {{ .Values.smartaiHome }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.smartaiHome }}
            - name: config
              mountPath: /opt/smartai/config.ini
              subPath: config.ini
            - name: config
              mountPath: {{ .Values.smartaiHome }}/cert_public.pem
              subPath: cert_public.pem
            {{- if .Values.storage.persisted }}
            - name: cache
              mountPath: /pip-cache
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "smartai.fullname" . }}
            items:
              - key: config.ini
                path: config.ini
              - key: cert_public.pem
                path: cert_public.pem
        {{- if not .Values.storage.persisted }}
        - name: data
          emptyDir: {}
        - name: cache
          emptyDir: {}
        {{- end }}
        {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.storage.persisted }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "smartai.labels" . | nindent 10 }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.volumeSize }}
        {{- if .Values.storage.storageClass }}
        storageClassName: {{ .Values.storage.storageClass }}
        {{- end }}
    - metadata:
        name: cache
        labels:
          {{- include "smartai.labels" . | nindent 10 }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.cacheVolumeSize | default "10Gi" }}
        {{- if .Values.storage.storageClass }}
        storageClassName: {{ .Values.storage.storageClass }}
        {{- end }}
  {{- end }}