apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dhis2-core-helm.fullname" . }}
  labels:
    {{- include "dhis2-core-helm.labels" . | nindent 4 }}
data:
  dhis.conf: |
    {{- .Values.dhisConfig | nindent 4 }}
  server.xml: |
    {{- .Files.Get .Values.serverXml | nindent 4 }}
