apiVersion: v1
kind: Service
metadata:
  name: {{ include "tritonserver.fullname" . }}
  labels:
    {{- include "tritonserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default 8000 }}
      targetPort: http
      protocol: TCP
      name: http-inference-server
    - port: 8001
      targetPort: grpc
      name: grpc-inference-server
    - port: 8002
      targetPort: metrics
      name: metrics-inference-server
  selector:
    {{- include "tritonserver.selectorLabels" . | nindent 4 }}
