name: Release Charts

on:
  push:
    branches:
      - master
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Add helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add superset https://apache.github.io/superset
          helm repo add trino https://trinodb.github.io/charts
          helm repo add jetstack https://charts.jetstack.io
          helm repo add starrocks https://starrocks.github.io/starrocks-kubernetes-operator
          helm repo add opensearch https://opensearch-project.github.io/helm-charts
          helm repo add apache-solr https://solr.apache.org/charts
          helm repo add ollama-helm https://otwld.github.io/ollama-helm/
          helm repo update
          helm dependency update charts/core
          helm dependency update charts/dashboard
          helm dependency update charts/kafka
          helm dependency update charts/certmanager
          helm dependency update charts/smartai
          helm dependency update charts/tritonserver
          helm dependency update charts/web
          helm dependency update charts/byod
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
